"use client"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { BookOpen, Brain, Zap, Users, Sparkles } from "lucide-react"
import { cn } from "@/lib/utils"
import { Spotlight } from "@/component/spotlight"
import { LearningInput } from "@/component/LearningInput"
import { PopularTags } from "@/component/PopularTags"
import { HeroHeading } from "@/component/heading"
import { useRouter } from "next/navigation"
import { useState } from "react"

export default function HomePage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);

  const navigateToCourse = (rawTag: string) => {
    const cleanTag = rawTag.replace(/^#/, "").trim();
    if (!cleanTag) return;
    setLoading(true);
    router.push(`/courses/${encodeURIComponent(cleanTag)}`);
  };

  const handleInputSubmit = (tags: string) => {
    navigateToCourse(tags);
  }


  const handleTagClick = (tag: string) => {
    navigateToCourse(tag);
  };

  return (
    <div className="relative min-h-screen overflow-hidden bg-black text-white">
      <Spotlight className="-top-40 left-0 md:-top-20 md:left-60" fill="#5b91ff" />

      <main className="relative z-10 mx-auto max-w-6xl px-6 py-16 md:px-8 lg:py-24">
        {/* Hero Section */}
        <section className="mb-12 text-center">
          <HeroHeading />
          <p className="mx-auto mt-4 max-w-2xl text-balance text-neutral-400">
            Generate tailored learning paths with AI. Type what you want to learn or pick a popular topic.
          </p>
          <div className="mx-auto mt-8 max-w-2xl">
            <LearningInput onSubmit={handleInputSubmit} />
          </div>
        </section>

        {/* Popular Tags */}
        <section className="mb-16">
          <PopularTags onTagClick={handleTagClick} />
        </section>

        {/* Feature Grid */}
        <section className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          <Card className="bg-neutral-900/60 border border-neutral-800 p-6">
            <div className="flex items-center gap-3">
              <BookOpen className="h-6 w-6 text-blue-400" />
              <h3 className="font-semibold">Structured Learning</h3>
            </div>
            <p className="mt-2 text-sm text-neutral-400">
              Courses are broken into clear modules and lessons, tailored to your topic.
            </p>
          </Card>
          <Card className="bg-neutral-900/60 border border-neutral-800 p-6">
            <div className="flex items-center gap-3">
              <Brain className="h-6 w-6 text-purple-400" />
              <h3 className="font-semibold">AI-Powered</h3>
            </div>
            <p className="mt-2 text-sm text-neutral-400">
              Lessons are generated by AI based on your input for the most relevant guidance.
            </p>
          </Card>
          <Card className="bg-neutral-900/60 border border-neutral-800 p-6">
            <div className="flex items-center gap-3">
              <Zap className="h-6 w-6 text-yellow-400" />
              <h3 className="font-semibold">Fast & Focused</h3>
            </div>
            <p className="mt-2 text-sm text-neutral-400">
              Get a complete course outline in seconds, ready to start learning.
            </p>
          </Card>
          <Card className="bg-neutral-900/60 border border-neutral-800 p-6">
            <div className="flex items-center gap-3">
              <Users className="h-6 w-6 text-emerald-400" />
              <h3 className="font-semibold">For All Levels</h3>
            </div>
            <p className="mt-2 text-sm text-neutral-400">
              Whether beginner or advanced, content adapts to your needs.
            </p>
          </Card>
        </section>

        {/* CTA */}
        <section className="mt-10 text-center">
          <button
            onClick={() => navigateToCourse("React")}
            className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white shadow-lg transition hover:bg-blue-700"
          >
            <Sparkles className="h-5 w-5" /> Generate a React Course
          </button>
        </section>
      </main>

      {loading && (
        <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 backdrop-blur-sm">
          <div className="h-12 w-12 animate-spin rounded-full border-4 border-blue-400 border-t-transparent" />
        </div>
      )}
    </div>
  )
}
